hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 8192
  train_batch_size: 8
  return_raw_chat: True
  filter_overlong_prompts: True
  truncation: error

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_user_turns: 30
      max_assistant_turns: 30
